---
openapi: 3.0.0
info:
  description: Practice API for Learning Swagger 
  version: 1.0.0
  title: Practice API for Learning Swagger 
  contact: 
    name: Marshall Onsrud
    email: marshall@theonsruds.com
    url: https://www.linkedin.com/in/marshallonsrud/  
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:

  "/uptime":
    get:
      description: Get the uptime for the system
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  uptime:
                    type: string

  "/date":
    get:
      description: Get the date from the system
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  date:
                    type: string

  "/uname":
    get:
      description: Get the uname from the system
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  uname:
                    type: string                    

  "/memory":
    get:
      description: Get the memory utilization for the system in kB
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_memory:
                    type: integer
                  available_memory:
                    type: integer
                  free_memory:
                    type: integer
  "/df":
    get:
      description: Get the disk utilization for the system
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  device:
                    type: string
                  space_used:
                    type: integer 
                  space_available:
                    type: integer 
                  percent_used:
                    type: string

  "/cpu":
    get:
      description: Get the cpu information for the system
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  cpu_model:
                    type: string
                  cpu_mhz:
                    type: float
                  cpu_cores:
                    type: integer

servers:
- url: http://127.0.0.1:8080/practice/1.0.0

